// Users
// Create Account
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName": "Polo",
    "department": "Admin",
    "email": "marc.hamacek@gmail.com",
    "password": "$Polochon33"
}

###

// Login account
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "marcopolo@gmail.com",
    "password": "$Polochon33"
}

###
// Get All Users / One User
GET http://localhost:5000/users

###
// Update User Profile
PUT http://localhost:5000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQyOTkzMDUsImV4cCI6MTYyNDM4NTcwNX0.lf2pmemVaPuWisv6kn_TvauO_Urulv-tVJQVUCDBhnw
Content-Type: application/json

{
    "firstName": "Marcos",
    "lastName": "Polos",
    "department": "Admin",
    "email": "marcouspolous@gmail.com",
    "password": "1234"
}

###
// Delete user account
DELETE http://localhost:5000/users/2


###

// Posts
// Create a post
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ4OTA3NzAsImV4cCI6MTYyNDk3NzE3MH0.71k1lKi13heD3ogNp6RwhYZm5XLXuU0X1xMEl6MIXLs

{
    "content": "Test pour Delete comment"
}

###
// Get all posts
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ4OTA3NzAsImV4cCI6MTYyNDk3NzE3MH0.71k1lKi13heD3ogNp6RwhYZm5XLXuU0X1xMEl6MIXLs

###
// Get one post
GET http://localhost:5000/posts/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ4OTA3NzAsImV4cCI6MTYyNDk3NzE3MH0.71k1lKi13heD3ogNp6RwhYZm5XLXuU0X1xMEl6MIXLs

###
// Update a post
PUT http://localhost:5000/posts/28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

{
    "content": "Test update réussi ?"
}

###
// Delete a post
DELETE http://localhost:5000/posts/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzNzc0NjY2LCJleHAiOjE2MjM4NjEwNjZ9.TQWtBy38i90yKYfJuNb73M09vGncrucJDQZ93vNGNJE

###
// Comments
// Create a comment on a post
POST http://localhost:5000/posts/12/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ4OTA3NzAsImV4cCI6MTYyNDk3NzE3MH0.71k1lKi13heD3ogNp6RwhYZm5XLXuU0X1xMEl6MIXLs
Content-Type: application/json

{
    "content": "Test Commentaire pour delete",
    "PostId": "12",
    "UserId": "5"
}


###
// Get all comments from a post
GET http://localhost:5000/posts/comments/18

###
// Delete a comment
DELETE http://localhost:5000/posts/comments/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQ4OTA3NzAsImV4cCI6MTYyNDk3NzE3MH0.71k1lKi13heD3ogNp6RwhYZm5XLXuU0X1xMEl6MIXLs
